---
abstract: 'framework for laconic DBI'
author:
  - 'Oleksandr Kharchenko <okharch@okharch.com>'
build_requires:
  DBD::SQLite: 1.27
  ExtUtils::MakeMaker: 6.66
  Parse::CPAN::Meta: 1.4404
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Brev
no_index:
  directory:
    - t
    - inc
requires:
  Config::General: 2.51
  DBI: 1.625
  DBIx::Connector: 0.53
  SQL::SplitStatement: 1.0002
version: 0.01
